site_name: projeto <i>QueriDO</i>
pages:
    - Documentação: index.md
    - Histórico: historico.md
    - Curadorias: 
        - Regulamento: curadorias.md
        - Curadoria-1: reports/curadoria001.md
        - Curadoria-3: reports/curadoria003.md
    - Relatórios:
        - Relatório-1.1: reports/curadoria001/report01.md
    - Ferramentas: 
        - Apresentação: ferramentas.md
        - TrazDia: trazdia-uso.md 
        - Diário Livre: diarioLivre-uso.md 
        - Poppler: poppler-uso.md
theme_dir: src/okbr_theme

